default_provider = "age"

[providers.age]
type = "age"
key_file = "~/.ssh/id_ed25519"
recipients = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJGE0QUW2CqfwANxZCCcXNGPM2RoMmwOqtXobEOl1vfm", # Max
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINmDNdk9RSsjCqR11cdsA6lWSHdlb2ZnCbF78XyZrfvh", # Tim (from github)
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID6QaWxEU9x9zSt7TRoPIlmCILKA2LHkVtlmEXvJpK/5" # Tim (from github)
]

[profiles]

[profiles.maintainers.providers.age]
type = "age"
key_file = "~/.ssh/id_ed25519"
recipients = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJGE0QUW2CqfwANxZCCcXNGPM2RoMmwOqtXobEOl1vfm", # Max
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINmDNdk9RSsjCqR11cdsA6lWSHdlb2ZnCbF78XyZrfvh", # Tim (from github)
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID6QaWxEU9x9zSt7TRoPIlmCILKA2LHkVtlmEXvJpK/5" # Tim (from github)
]

[profiles.maintainers.secrets]
AZURE_STORAGE_SAS_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNPTitDUSBGYXJiMENVbFk2WXpaMnpkUlZUbjNiMlpmQUF3elZraEZvZ3JrMjFKT3djCndmSFc0SGZsZXR2eTMwMHplSXdzSmt1cmFiWWxDK01remY5TjJ1cE91NFEKLT4gc3NoLWVkMjU1MTkgV1ZEaHZnIEJXRkR6OUZvK3VPM0dnL3UrWUlwT2RCYzM0UGFBNGVHOFR2aXhrTEduUkkKMjJhRlpsbEJXWTBOd2dMaWhXNVd5RW9GYVJTbExNelJDT09NZnhpTk9XMAotPiBzc2gtZWQyNTUxOSA5Q3hlWHcgRXBJRW11WHl5OU9iYUhlWVdrNHJmQjY3TnFQVUdsU1lmaFlGL1NNUEFuQQpSbVc0RVVRUjUvVDlSSkZPYzlGNW1pam14UlhiMHF0ZWJjZjlJZGR2Z1hZCi0+IGxremMtZ3JlYXNlIHd2ICtGdFFMIGJmWGN1VSFTCjNhVmE1eVNyRTJ3MgotLS0gNXBiZWpaU0pnV2ltZTBmTURsSTl0VEY4LzhaNmkxN1MvNEZHT2NmaDVXRQpERncjX1vZNJZrr0/Ln/VdIHNpNQ2KGBKTVS22ytYE9v20R4maqkJv7ZiNjD9g7ye89fJsQZRXLW7yXBF6dEv5OZpxMOMjZyP3QAQ8aiuuOkgx3JRETgqc05gf+60PdP4nIsnkGtEc491IqRixLSjz/FrYargtk4X3QfQeVU0jKrsI1T7fisEbvE8kheuwdSPnZ4RZXXiLTzvb", description = "Read-write-delete token for Azure storage container." }

[secrets]
AZURE_STORAGE_SAS_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNPTitDUSAwWHhrNVg4VHRmMkZnZUxxdEx4NDFBbGo3QmxCZCs4UXBhMFRmVlFxVDMwCnZtNW1IbUtpbUZxaE1icS9Gc2lXOGV2ZkJTSmtnQWxlanJCQjJ4UkpyT1UKLT4gc3NoLWVkMjU1MTkgV1ZEaHZnIHF3WnJGQUdWazMwN2ZwQkQ4K0NZTk1UOUhubmFadzlvSU1TWHJ3Ym1vd2MKdmRuK2lNQkZNdkNkWTNXc0lJUUxVNjVyUmxMdCs1YXRJRkxQSHR0VE1tNAotPiBzc2gtZWQyNTUxOSA5Q3hlWHcgK2drMHovS2U5allkY3RlQ21RNURhSW5lc1ZjYTliWmhZbHYxN3BVKzdIbwp6NC9rMXZvNURkWU5aQ0RxU2drS0hsVDEyTDRoZzgrL0lWWlZXWmpKT1hrCi0+ID17ITFkRy1ncmVhc2UgdQp5azhvQmVIZWdKcXRpMnZKdEFqSUR6T3l6V1hxcXJFK2M5UnhCM0FFajFKdE0zdE5lTWdWWnVvcjdZUEFBcWQ0CnhDVk1DUkVYVExscG1SbXlyMFRJZDV6MEhvNDV4ZjY2VkpiNGN2eEkKLS0tIDJUKzIzaTJkUmFnNHhSVUtvY0NaN2NoNEdpZEhCZ1lVWnduL0U5SXFmT00KJlySIUa+2g0Iol2s0bPugaDE0aVcZgzoFR6KaHazbASwPbX4aciIzXcpArjGyrQGgZ4oZCj5JTnjnlEkkoc+bEU4qAs+3F5rMHDO7KTzJ0yHojEFO4E4IgoJxvwxX5u+EifavfzEa93L+yZVJ6NE9n3sKzzkq5E03bNyIuGkGhGcKNUP9iAI4lZfjrpikq8svUkfhtKFikNp+n5L", description = "Read-write token for Azure storage container. Can't be used to delete data." }
