default_provider = "age"

[providers.age]
type = "age"
key_file = "~/.ssh/id_ed25519"
recipients = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJGE0QUW2CqfwANxZCCcXNGPM2RoMmwOqtXobEOl1vfm", # Max
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINmDNdk9RSsjCqR11cdsA6lWSHdlb2ZnCbF78XyZrfvh", # Tim (from github)
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID6QaWxEU9x9zSt7TRoPIlmCILKA2LHkVtlmEXvJpK/5" # Tim (from github)
]

[profiles]

[profiles.maintainers.providers.age]
type = "age"
key_file = "~/.ssh/id_ed25519"
recipients = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJGE0QUW2CqfwANxZCCcXNGPM2RoMmwOqtXobEOl1vfm", # Max
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINmDNdk9RSsjCqR11cdsA6lWSHdlb2ZnCbF78XyZrfvh", # Tim (from github)
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID6QaWxEU9x9zSt7TRoPIlmCILKA2LHkVtlmEXvJpK/5" # Tim (from github)
]

[profiles.maintainers.secrets]
AZURE_STORAGE_SAS_TOKEN= { provider = "age", value = "fnox-age-batch-v1:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNPTitDUSBYaFhGL3dZa2UvbWFINmx5aG9qNjlMK3o5ei8xWVowWGxnZ255bTFFZTJRClhwOSt5UW5IUDNhYWxPOWlaeHVKZFR3QUJsbHA0ZjlKVEVYMWkreHZxdDgKLT4gc3NoLWVkMjU1MTkgV1ZEaHZnIFg0MFBRMzVCR1JCRlkvUDB5T2RGYXRiOWExWTRaNGJVNjRRSStkMFVFeDAKRlQwNEduRFdtRUk1SVZqR0J0ZVNnVUpMazVsaEJ2dmg3cFNNcU1wRTFJawotPiBzc2gtZWQyNTUxOSA5Q3hlWHcgUXdaVHlQdFROOU9JQ3A1YjlKanRZdFZxNGRZSVI4OFFNaVJ5TnFmajF5MApuempuM0xEMlp6ZFRxdkY2MGJlRTFaUUpUTjRkV0k2OURnVkNtaTFmT3dBCi0+IFokOn56LWdyZWFzZSB3JHcyI1UgbTEgM1tSUF8wIDg8P1FzTgppQ21ICi0tLSBjckxPenp4aXlCMUZMeFhXNkUvVGtCQXdUM3RkTmJqcnVSMStDOE5XTTBRCvE6zOwcO4ZuG3CYSk7RpOU2JHka1ueku6Vz7lqKdrKNcYg1JwX52uWGssVwlyCpVWaspJ8OVdNsgu9/Elkp8q386WpC5Foc9CQBzRw=:/79xijC79VwEdJcU+YjAE3EKR+shD4wQwEAlI72di7Q8CRvg/eWyw5HOFSEW6E6dCJBCxatEjcUt0m3JDAMUDAbneVdFaSTL3irHBRxiscmSla1iwPOZXRDchLli28HexMa23V83w+cWIW5wpJOwzjeE3NVtYT0pCfU6HKulAGpJ/ana8KVtkmbFIYhuVZtsWxl2jMP3WTk=", description = "Read-write token for Azure storage container" }

[secrets]
AZURE_STORAGE_SAS_TOKEN= { provider = "age", value = "fnox-age-batch-v1:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNPTitDUSBNeTdoLzZ3OHNudlp3eSt2M01RN0psQStHOUlrZVYvTGE0YmJxZVA4bUZjCmlrRzZpQTIwRkYvamhDQVViY2MxeGdHUmMwcjI4S0Q4NGtIRWk0akhCR3cKLT4gc3NoLWVkMjU1MTkgV1ZEaHZnIGpPNnljcXQ0UTR0eG94MHBsZ0ZtTmxQYWRjcG9mTWhKaHgyZ0VaV2MyREEKQk1rbkhQYTBoanRkaitJeldlYWQreXlFeUJDZFkza3JHWVpCZlJic3l4WQotPiBzc2gtZWQyNTUxOSA5Q3hlWHcgLzBUTTNZQmRYWURGaW1ub1ZGOHh4UDUwWE8vQXJNcDYxU1FDYU1pT013WQo1UVBneHhKSXhPNkF2UFZzOGhLY2tLMENzekZDTW5QdmR5eWdjbE8xb1pFCi0+IExVfC1ncmVhc2UgMm9qLklKSkwgKFdydTggJH45fnxCCmdhSUNYcDFYR21uYldlMGpDcW1PQkdHWmswV3JqckNiV3RyQjcyekg3V1Y3MUU4WTdTZmQwcWNCdUtZbVBJSFEKRFZYclpyU1A4OFg1S2pDa3FnT1JIdVlwSzR4aXlOa0xtZwotLS0gQXdlTXIzVHN0ZjNRTlNHa09YVWJTaWNtOEhHTjQ4VXNKTGVpR2w0TlBlYwopEYPshYiUUstpJlEtC12HdqxJ1+n1oq3fwY2XSpxeGy7jfq91FoZk52FlKkoMgkKqNkdJ5GQkH9uvKjm2xcjYKDMz2f0WrdJOIrFV:BnmF8ltupN4A1x+Wz6hew36bN2KVdTazkYJ1eUezg0k1NAnWIc6myslxlF04NNWBqBhO4n2mI2v6HTC/qNNyftDqJfQEMOHk+wQ14Lw5hciuDcHIplJUmbrmIWy2EvOfUfoeQSG8oiKcnj7oPy7jgnPVim/BFoTBpE7/uxsh4m3MpvCr7rWPvVkAYSva1alS", description = "Read-only token for Azure storage container" }
